version: 0.2

phases:
  install:
    commands:
      - echo "Installing AWS CLI..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
  build:
    commands:
      - echo "Build step..."
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 cp index.html s3://your-unique-bucket-name/index.html

artifacts:
  files:
    - index.html
